// This file is auto-generated by @hey-api/openapi-ts

export const $CreateTaskData = {
    type: 'object',
    required: ['task_type', 'data'],
    properties: {
        data: {
            type: 'object',
            additionalProperties: {
                type: 'string'
            }
        },
        task_type: {
            type: 'string'
        }
    }
} as const;

export const $ErrorResponse = {
    type: 'object',
    required: ['status', 'error'],
    properties: {
        error: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $LoginData = {
    type: 'object',
    required: ['username', 'password'],
    properties: {
        password: {
            type: 'string'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const $ResponseCreateTask = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            '$ref': '#/components/schemas/Task'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $ResponseDeleteAllTasksForUser = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $ResponseDeleteTaskByIdForUser = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $ResponseListTasks = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Task'
            }
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $ResponseLogin = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $ResponseMe = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            '$ref': '#/components/schemas/UserReturn'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $ResponseSignUp = {
    type: 'object',
    required: ['status', 'data'],
    properties: {
        data: {
            '$ref': '#/components/schemas/UserReturn'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const $SignUpData = {
    type: 'object',
    required: ['username', 'email', 'password', 'repeat_password'],
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        repeat_password: {
            type: 'string'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const $Task = {
    type: 'object',
    required: ['id', 'created_at', 'type_', 'data', 'user_id'],
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        data: {},
        id: {
            type: 'string',
            format: 'uuid'
        },
        type_: {
            type: 'string'
        },
        user_id: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const $UserReturn = {
    type: 'object',
    required: ['id', 'username', 'email'],
    properties: {
        email: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        username: {
            type: 'string'
        }
    }
} as const;