// This file is auto-generated by @hey-api/openapi-ts

export type CreateTaskData = {
    data: {
        [key: string]: (string);
    };
    task_type: string;
};

export type ErrorResponse = {
    error: string;
    status: string;
};

export type LoginData = {
    password: string;
    username: string;
};

export type ResponseCreateTask = {
    data: Task;
    status: string;
};

export type ResponseDeleteAllTasksForUser = {
    data: string;
    status: string;
};

export type ResponseDeleteTaskByIdForUser = {
    data: string;
    status: string;
};

export type ResponseListTasks = {
    data: Array<Task>;
    status: string;
};

export type ResponseLogin = {
    data: string;
    status: string;
};

export type ResponseMe = {
    data: UserReturn;
    status: string;
};

export type ResponseSignUp = {
    data: UserReturn;
    status: string;
};

export type SignUpData = {
    email: string;
    password: string;
    repeat_password: string;
    username: string;
};

export type Task = {
    created_at: string;
    data: unknown;
    id: string;
    type_: string;
    user_id: string;
};

export type UserReturn = {
    email: string;
    id: string;
    username: string;
};

export type ListTasksData = {
    /**
     * Auth token
     */
    xApiAuthToken: string;
};

export type ListTasksResponse = ResponseListTasks;

export type CreateTaskData2 = {
    requestBody: CreateTaskData;
    /**
     * Auth token
     */
    xApiAuthToken: string;
};

export type CreateTaskResponse = ResponseCreateTask;

export type DeleteAllTasksForUserData = {
    /**
     * Auth token
     */
    xApiAuthToken: string;
};

export type DeleteAllTasksForUserResponse = ResponseDeleteAllTasksForUser;

export type DeleteTaskByIdForUserData = {
    /**
     * Task id
     */
    taskId: string;
    /**
     * Auth token
     */
    xApiAuthToken: string;
};

export type DeleteTaskByIdForUserResponse = ResponseDeleteTaskByIdForUser;

export type LoginData2 = {
    requestBody: LoginData;
};

export type LoginResponse = ResponseLogin;

export type MeData = {
    /**
     * Auth token
     */
    xApiAuthToken: string;
};

export type MeResponse = ResponseMe;

export type SignupData = {
    requestBody: SignUpData;
};

export type SignupResponse = ResponseSignUp;

export type $OpenApiTs = {
    '/api/v1/rzd/tasks': {
        get: {
            req: ListTasksData;
            res: {
                /**
                 * OK
                 */
                200: ResponseListTasks;
                /**
                 * Unauthorized
                 */
                401: ErrorResponse;
                /**
                 * INTERNAL_SERVER_ERROR
                 */
                500: ErrorResponse;
            };
        };
        post: {
            req: CreateTaskData2;
            res: {
                /**
                 * OK
                 */
                200: ResponseCreateTask;
                /**
                 * Data is not valid
                 */
                400: ErrorResponse;
                /**
                 * Unauthorized
                 */
                401: ErrorResponse;
                /**
                 * INTERNAL_SERVER_ERROR
                 */
                500: ErrorResponse;
            };
        };
        delete: {
            req: DeleteAllTasksForUserData;
            res: {
                /**
                 * OK
                 */
                200: ResponseDeleteAllTasksForUser;
                /**
                 * Unauthorized
                 */
                401: ErrorResponse;
                /**
                 * INTERNAL_SERVER_ERROR
                 */
                500: ErrorResponse;
            };
        };
    };
    '/api/v1/rzd/tasks/{task_id}': {
        delete: {
            req: DeleteTaskByIdForUserData;
            res: {
                /**
                 * OK
                 */
                200: ResponseDeleteTaskByIdForUser;
                /**
                 * Unauthorized
                 */
                401: ErrorResponse;
                /**
                 * Task not found for user
                 */
                404: ErrorResponse;
                /**
                 * INTERNAL_SERVER_ERROR
                 */
                500: ErrorResponse;
            };
        };
    };
    '/api/v1/users/login': {
        post: {
            req: LoginData2;
            res: {
                /**
                 * OK
                 */
                200: ResponseLogin;
                /**
                 * Data is not valid
                 */
                400: ErrorResponse;
            };
        };
    };
    '/api/v1/users/me': {
        get: {
            req: MeData;
            res: {
                /**
                 * OK
                 */
                200: ResponseMe;
                /**
                 * Unauthorized
                 */
                401: ErrorResponse;
                /**
                 * Internal server error
                 */
                500: ErrorResponse;
            };
        };
    };
    '/api/v1/users/signup': {
        post: {
            req: SignupData;
            res: {
                /**
                 * OK
                 */
                200: ResponseSignUp;
                /**
                 * Data is not valid
                 */
                400: ErrorResponse;
            };
        };
    };
};