version: "3.1"

services:
  db:
    image: surrealdb/surrealdb
    user: root
    ports:
      - "8080:8080"
    volumes:
      - db-data:/data/
    command: "start -A --log trace --auth --user root --pass root --bind 0.0.0.0:8080 file://data/db.db"
    restart: on-failure

volumes:
  db-data:
networks:
  main_network:
