version: "3.1"

services:
  pg:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=metools
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - main_network

volumes:
  pg_data:
networks:
  main_network: